### ISSUE TITLE
Foltilla binary only works on ARM.

### ISSUE THREAD

**Issue by choffee** [pimoroni/flotilla-offline#1]
Hi,
I don't have a spare Pi to run this on right now. Could you include an Intel build of the flotilla binary?

**Comment by Gadgetoid** [comment]
It wasn't something we were going to shout about at launch, but it can be done. Windows, Linux or OSX? ( haven't tried building for x86 Linux yet actually )

**Comment by choffee** [comment]
Linux would be great. But others might want the other platforms. Is there source available? I don't mind compiling it.

**Comment by Gadgetoid** [comment]
Source is now available here, with a Makefile for OSX/Linux compilation: https://github.com/pimoroni/Flotilla-Daemon-VS

**Comment by Gadgetoid** [comment]
Marking this as "wontfix" because Flotilla Offline is designed for installation on the Raspberry Pi only. Installers for Windows and Mac OS, when they happen, will certainly differ.
